server:
  port: 8080
  servlet:
    context-path: /


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shouyi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    type: com.alibaba.druid.pool.DruidDataSource




  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


mybatis:
  type-aliases-package: com.sy.watersupplysystem.entities
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    use-actual-param-name: true

logging:
  level:
    com:
      sy:
        watersupplysystem:
          mapper: debug